### ISSUE TITLE
Is this package maintened by newrelic ?

### ISSUE THREAD

**Issue by billouboq** [newrelic-experimental/NewRelicReactNativeModule#20]
Hi, 

I'm starting to newrelic but it seems this react-native module isn't maintened. Is there any work planned by NewRelic on improving react-native support ?

**Comment by dougkeen** [comment]
See https://discuss.newrelic.com/t/experimental-react-native-support/115888 and https://docs.newrelic.com/docs/mobile-monitoring/new-relic-monitoring-react-native/monitor-your-react-native-application/, but note that javascript errors are currently only reported as custom events and don't support automatic symbolication (you have to do that manually in your local env).

I think it's safe to say this library is deprecated.

**Comment by billouboq** [comment]
Thank you very much !
